---

host_email_address: "bfrank@oreilly.com"
onepassword_vault: "Employee"
desktop_app_paths:
  - "/Applications"
  - "{{ ansible_facts['user_dir'] }}/Applications/Chrome Apps.localized"

git_clone_repos:
  - url: "git@github.com:bradleyfrank/ansible.git"
  - url: "git@github.com:bradleyfrank/notes-etc.git"
  - url: "git@github.com:bradleyfrank/util-containers.git"
  - url: "git@github.com:bradleyfrank/cliday.git"

packages_homebrew_casks:
  - "1password"
  - "1password-cli"
  - "alacritty"
  - "appcleaner"
  - "google-cloud-sdk"
  - "itsycal"
  - "keepingyouawake"
  - "maccy"
  - "multipass"
  - "rectangle"
  - "utm"
  - "vlc"
  - "zoom"

packages_mas_apps: []

zsh_completions:
  - name: "kubectl"
    command: "kubectl completion zsh"
  - name: "stern"
    command: "kubectl stern --completion=zsh"
  - name: "k9s"
    command: "k9s completion zsh"
  - name: "cht"
    command: "curl -L https://cheat.sh/:zsh"
  - name: "nb"
    command: "curl -L https://raw.githubusercontent.com/xwmx/nb/master/etc/nb-completion.zsh"

system_macos_sleep_display: -1
system_macos_sleep_computer: -1
