---

bat_exec: "/usr/bin/batcat"
tmux_clipboard: "wl-copy"

system_linux_dconf_distro:
  - path: "/org/gnome/desktop/interface"
    keys:
      gtk-theme: "'Yaru-light'"
  - path: "/org/gnome/shell"
    keys:
      disabled-extensions: "[\
        'ding@rastersoft.com',
        'window-list@gnome-shell-extensions.gcampax.github.com',
        'horizontal-workspaces@gnome-shell-extensions.gcampax.github.com',
        'places-menu@gnome-shell-extensions.gcampax.github.com',
        'ubuntu-dock@ubuntu.com',
        'workspace-indicator@gnome-shell-extensions.gcampax.github.com']"
      enabled-extensions: "[\
        'GPaste@gnome-shell-extensions.gnome.org',
        'launch-new-instance@gnome-shell-extensions.gcampax.github.com',
        'auto-move-windows@gnome-shell-extensions.gcampax.github.com',
        'ubuntu-appindicators@ubuntu.com']"
      favorite-apps: "[\
        'org.gnome.Terminal.desktop',
        'firefox_firefox.desktop',
        'org.gnome.Nautilus.desktop',
        '1password.desktop',
        'org.gnome.gedit.desktop',
        'org.signal.Signal.desktop']"

packages_apt_repos:
  - name: google-chrome
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    key: https://dl.google.com/linux/linux_signing_key.pub
  - name: gh-cli
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg]
      https://cli.github.com/packages stable main
    key: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg
  - name: charm
    repo: deb [trusted=yes] https://repo.charm.sh/apt/ /
    key: https://apt.fury.io/charmcli/gpg.key
    keyring: /usr/share/keyrings/charmcli.gpg

packages_apt_packages:
  cli:
    - apt-file
    - atool
    - bash-completion
    - bat
    - bcal
    - black
    - borgbackup
    - diceware
    - dictd
    - duf
    - fd-find
    - fdupes
    - ffmpeg
    - figlet
    - fwupd
    - fzf
    - gh
    - ghostscript
    - glances
    - htop
    - httpie
    - iftop
    - inxi
    - jq
    - libmp4-info-perl
    - libvirt-clients
    - mkvtoolnix
    - most
    - msmtp
    - mtr
    - nmap
    - p7zip-*
    - par
    - perf-tools-unstable
    - pdfgrep
    - pipx
    - pwgen
    - python3
    - python3-dev
    - python3-pip
    - ripgrep
    - ruby
    - shellcheck
    - ssh
    - stow
    - strace
    - tidy
    - tlp
    - tmux
    - tmuxp
    - toilet
    - tree
    - trurl
    - vim
    - virtualenv
    - wget
    - xdelta
    - xz-utils
    - yt-dlp
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
  gui:
    - 1password
    - alacritty
    - asciinema
    - audacious
    - calibre
    - drawing
    - fonts-noto-color-emoji
    - ghostwriter
    - google-chrome-stable
    - keepassxc
    - libreoffice
    - nextcloud-desktop
    - picard
    - remmina
    - shutter
    - solaar
    - system-config-printer
    - timeshift
    - torbrowser-launcher
    - vlc
  gnome:
    - celluloid
    - geary
    - gedit-plugin-code-comment
    - gedit-plugin-color-picker
    - gedit-plugin-git
    - gedit-plugin-join-lines
    - gedit-plugin-multi-edit
    - gnome-characters
    - gnome-connections
    - gnome-games-app
    - gnome-keyring
    - gnome-shell-extension-manager
    - gnome-shell-extensions
    - gnome-shell-extensions-gpaste
    - gnome-sushi
    - gnome-tweaks
    - gnote
    - gpaste*
    - gthumb
    - meld
    - mpv
    - transmission-gtk
  cinnamon:
    - celluloid
    - gpaste*
    - meld
    - mpv
    - transmission-gtk

packages_homebrew_taps:
  - charmbracelet/tap

packages_homebrew_formulas:
  - atuin
  - bat-extras
  - csvlens
  - doctl
  - eza
  - fastfetch
  - freeze
  - glow
  - lazygit
  - nb
  - qsv
  - yq
